// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejbabotmowzixfhsebda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqYmFib3Rtb3d6aXhmaHNlYmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDQ3NDYsImV4cCI6MjA2MTY4MDc0Nn0.n2zWqOFd1zsdzMEJY5D0ExvfWgUcXYYwjDFw3vYBqro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);